ngx-top-build-ubuntu-12.04:
  image: ubuntu:12.04
  container_name: ngx-top-build-container-ubuntu-12.04 # to have fixed name
  volumes:
  - ./build:/build
  - .:/src/ngx-top
  working_dir: /tmp
  command: sh /src/ngx-top/build/docker-build-ubuntu.sh 12.04
ngx-top-build-ubuntu-14.04:
  image: ubuntu:14.04
  container_name: ngx-top-build-container-ubuntu-14.04 # to have fixed name
  volumes:
  - ./build:/build
  - .:/src/ngx-top
  working_dir: /tmp
  command: sh /src/ngx-top/build/docker-build-ubuntu.sh 14.04
ngx-top-build-ubuntu-16.04:
  image: ubuntu:16.04
  container_name: ngx-top-build-container-ubuntu-16.04 # to have fixed name
  volumes:
  - ./build:/build
  - .:/src/ngx-top
  working_dir: /tmp
  command: sh /src/ngx-top/build/docker-build-ubuntu.sh 16.04
ngx-top-build-static:
  image: mitchty/alpine-ghc:latest
  container_name: ngx-top-build-container # to have fixed name
  volumes:
  - ./build:/build
  - .:/src/ngx-top
  working_dir: /tmp
  command: sh /src/ngx-top/build/docker-build-static.sh
