ngx-top-build-ubuntu-16.04:
  image: ubuntu:16.04
  container_name: ngx-top-build-container-ubuntu-16.04 # to have fixed name
  volumes:
  - ./build:/build
  - .:/src/ngx-top
  working_dir: /tmp
  command: sh /src/ngx-top/build/docker-build-ubuntu.sh 16.04
ngx-top-build-ubuntu-18.04:
  image: ubuntu:18.04
  container_name: ngx-top-build-container-ubuntu-18.04 # to have fixed name
  volumes:
  - ./build:/build
  - .:/src/ngx-top
  working_dir: /tmp
  command: sh /src/ngx-top/build/docker-build-ubuntu.sh 18.04
